### ISSUE TITLE
RegressionResult

### ISSUE THREAD

**Issue by floswald** [jmboehm/RegressionTables.jl#1]
hey,
looks great! so here is what I have been thinking. there is an abstract type in StatsBase called `RegressionResult` with a bunch of useful methods: http://juliastats.github.io/StatsBase.jl/stable/statmodels.html#Abstraction-for-Statistical-Models-1

you could tweak your code to, for example, nicely print the `coeftable` method, and add a bunch of other statistics. Ideally the FixedEffects.jl would deliver a `RegressionResult`? 

anyway good job!

**Comment by floswald** [comment]
for example, you can see that the GLM.jl package does 

```
    import StatsBase: coef, coeftable, confint, deviance, nulldeviance, dof, dof_residual, loglikelihood, nullloglikelihood, nobs, stderr, vcov, residuals, predict, fit, model_response, r2, r², adjr2, adjr², PValue
```

it just imports those types and then overloads each method:

```julia
function confint(obj::LinearModel, level::Real)
    hcat(coef(obj),coef(obj)) + stderr(obj) *
    quantile(TDist(dof_residual(obj)), (1. - level)/2.) * [1. -1.]
end
```

**Comment by jmboehm** [comment]
Addressed in PR #2

**Comment by floswald** [comment]
really cool!

**Comment by lbittarello** [comment]
Hi! Isn't `DataFrameRegressionModel` being phased out? Why not accept `RegressionModel` or even `StatisticalModel` from StatsBase?
