### ISSUE TITLE
LoadError: responsename is not defined for LinearMixedModel{Float64}.

### ISSUE THREAD

**Issue by jtrakk** [jmboehm/RegressionTables.jl#100]
I get an error from `regtable(::MixedModels.LinearMixedModel)`.
```
> regtable(modelfit)
LoadError: responsename is not defined for LinearMixedModel{Float64}.
  [ff71e718] MixedModels v3.8.0
  [d519eb52] RegressionTables v0.5.2
```

**Comment by jmboehm** [comment]
This is fixed by #101 and should be working in v0.5.3 (although the specific error message you got is because you're using an older version of MixedModels where `responsename` wasn't defined). Please let me know in case there are still issues.
