### ISSUE TITLE
Print `estimate` and statistic in one line 

### ISSUE THREAD

**Issue by danielw2904** [jmboehm/RegressionTables.jl#105]
Is it possible to print what is now the `below_statistic` in the same line as the estimate? It looks like the decorator only has access to the p-value which I would rather not report. However, especially on slides it is useful to have a "shorter" table. Stargazer has the `single.row` option that does that (see [p. 5 of Vignette](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf)).

**Comment by jmboehm** [comment]
Thanks. You're right, this seems to be not possible right now. But I'd be happy to review PR's that implement this.

**Comment by danielw2904** [comment]
Alright sounds great. I think it would be best to let the estim_decoration function take  coef and vcov instead of the p value. Then users can decide what they would like. Would it be ok for you if I implemented a keyword arg like stargazer’s single.row and then let the user pass a function that adds the statistic based on coef and vcov possibly with prebuilt options for Tstat, SE, and CI?
