### ISSUE TITLE
c align instead of r align?

### ISSUE THREAD

**Issue by floswald** [jmboehm/RegressionTables.jl#110]
hey
i have not found out how to produce a latex table that has `c` align for the results columns instead of the default `r`. I've seen this

```
function latexOutput(outfile::String = "")
    latexRegressandTransform(s::String,colmin::Int64,colmax::Int64) = "\\multicolumn{$(colmax-colmin+1)}{c}{$s}"
    latexTableHeader(numberOfResults::Int64, align::String) = "\\begin{tabular}{$align}"
    latexTableFooter(numberOfResults::Int64, align::String) = "\\end{tabular}"
```

but how do I pass the `align` argument into that function? thanks!

**Comment by jmboehm** [comment]
Yeah, the `align` string is being created in `render()` in a way that is currently not customizable-- we should change that. As a workaround in the meantime, you can define a function like https://github.com/jmboehm/RegressionTables.jl/blob/master/src/rendersettings/latex.jl (but with your desired table format) and pass this to the `renderSettings` option.

**Comment by floswald** [comment]
ok - I'm glad I didn't miss something totally obvious. 
So, if instead of 

```
    # construct alignment string:
    align = "l" * ("r" ^ numberOfResults)
```

we allow for a kwarg `align` in `regtable` that passes the `"r"` or the `"c"` as desired, would you accept that PR?

**Comment by jmboehm** [comment]
Yes, exactly. I don't think the `align` argument does anything in html or ascii output, but it would be good to check.
