### ISSUE TITLE
bootstrap confidence intervals

### ISSUE THREAD

**Issue by Gkreindler** [jmboehm/RegressionTables.jl#145]
I would like to extend `regtable` to a kind of RegressionModel that has a table with bootstrapped coefficient estimates. I would like to display a confidence interval based on those bootstrap results underneath each coefficient.

The new `below_statistic = ConfInt` option is really neat, but any new kind of `AbstractUnderStatistic` seems to only be allowed to depend on the SE, coefficient, and DOF. 

Would it be possible to add the entire model `rr` and the `k` index as arguments to `AbstractUnderStatistic`'s?
https://github.com/jmboehm/RegressionTables.jl/blob/0fb6d7dfda349a963efbd5702a2dc96e819b643b/src/regtable.jl#L521C56-L521C56

So go from the first line (current) to the second (proposal):
```
                coefbelow[j, i] = below_statistic(cur_stderror[k], cur_coef[k], _dof_residual(rr))
                coefbelow[j, i] = below_statistic(cur_stderror[k], cur_coef[k], _dof_residual(rr), rr, k)
```

Current implementations don't need this extra information. However, custom implementations of `below_statistic` can use all the info in `rr`. I think that I would then be able to implement a `below_statistic` that takes my RegressionModel extension and computes the 95% bootstrap CI.

Of course, apologies if I'm confused, and any suggestions much appreciated!

**Comment by junder873** [comment]
I think this is a reasonable point. Looking at it, I realize how inflexible the below statistics currently are. If you could take a look at #146 and let me know if that would fix your issue (I think it would), I would appreciate it. Happy to have suggestions to improve that request as well.
