### ISSUE TITLE
Is there a way to display "+" for p value between 5% and 10%？

### ISSUE THREAD

**Issue by dazhwu** [jmboehm/RegressionTables.jl#156]
I add default_breaks setting in the following code, expecting to see *** for 0.001, ** for 0.01, * for 0.05, and + for 0.10. But it doesn't work.
```
fereg=reg(high_ds, reg_formula, Vcov.robust()) 
println(regtable(fereg; render=AsciiTable(), default_breaks=[0.001,0.01,0.05,0.10]))
```
Also, below_statistic doesn't include P_Value which I believe is more informative than confidence interval when evaluating models.

**Comment by junder873** [comment]
There is not a built-in way to do either of those, but it is possible.

To make the "+" work, you can change the definition of `RegressionTables.estim_decorator`:
```julia
function RegressionTables.estim_decorator(render::AbstractRenderType, s, pval; args...)
    deco = if pval < 0.001
        "***"
    elseif pval < 0.01
        "**"
    elseif pval < 0.05
        "*"
    elseif pval < 0.1
        "+"
    else
        ""
    end
    if deco != ""
        deco = RegressionTables.wrapper(render, deco)
    end

    repr(render, s)*deco
end
```
That ignores the `default_breaks` argument, so if you want to change that throughout your tests, you would need to change the function a little more.

For a p-value, this is not built-in but it is very easy to make. Add to your code:
```julia
struct PValue <: RegressionTables.AbstractUnderStatistic
    val::Float64
end
PValue(rr::RegressionModel, k::Int; vargs...) = TStat(RegressionTables._pvalue(rr)[k])
```

Then you can run `regrtable(...; below_statistic=PValue)`

**Comment by dazhwu** [comment]
Thank you for your quick response.
