### ISSUE TITLE
Allow for space between coefficient rows

### ISSUE THREAD

**Issue by milonemario** [jmboehm/RegressionTables.jl#166]
Hi,

First of all, I would like to thank the authors of this package!
I have just started using it for my work (I am an academic researcher in social sciences), and the amount of customization allowed is incredibly useful.

There is one last thing I cannot manage to do (after looking at the doc and the source code).

The generated latex tables lack readability because there is no space between the different coefficients (coef + below statistics). The stargazer package in R includes an empty row between each coefficient to increase readability.

Do you know if it would be possible to include an option to add vertical spacing between the coefficient rows?
Alternatively, please let me know if there is a way to do it with the latest version I might have missed.

Thank you very much for your hard work and super helpful package!

**Comment by junder873** [comment]
Just to clarify, the goal here is the generated output (as opposed to the raw text having an extra line in between)?

**Comment by milonemario** [comment]
Yes, the idea is that the generated table includes an extra line.

For the Latex output, it would mean inserting a line that would look like " & & & \\" with the number of "&" depending on the number of columns so that the compiled output is more spaced.
For text output, it would just mean an extra line.
I'm not sure what the HTML output should be modified.

Thank you very much for your help!
