### ISSUE TITLE
Defining additional controls to be displayed with fixed effects

### ISSUE THREAD

**Issue by felixholub** [jmboehm/RegressionTables.jl#17]
I'm not sure if this is already possible:
Assume some of your explanatory variables consist of a group of variables. For example: age, sex, income are all information on demographics. I do not want to show each of the coefficients. This is achieved by not including them into `regressors`. However, I would like that in the lower part of the table I can have an entry together with the fixed effects, saying `Demograhics Yes`.
Is there a way to achieve that in RegressionTables?

**Comment by jmboehm** [comment]
Good point. Yes, that would definitely make sense.

**Comment by greimel** [comment]
I was just trying to use this feature and failed. Was this actually implemented?

I am reopening because this needs to documented either ways.

**Comment by jmboehm** [comment]
Yes, although I'm not super happy with the current interface and how it ends up looking. Here is the example from the tests:
```
using Statistics
comments = ["Baseline", "Preferred"]
means = [Statistics.mean(df.SepalLength[rr1.esample]), Statistics.mean(df.SepalLength[rr2.esample])]
mystats = NamedTuple{(:comments, :means)}((comments, means))
RegressionTables.regtable(rr1, rr2; renderSettings = RegressionTables.asciiOutput(joinpath(dirname(@__FILE__), "tables", "test9.txt")), regression_statistics = [:nobs, :r2],custom_statistics = mystats, labels = Dict("__LABEL_CUSTOM_STATISTIC_comments__" => "Specification", "__LABEL_CUSTOM_STATISTIC_means__" => "My custom mean") )
```
Here is how I use it:
```
labels = Dict("__LABEL_CUSTOM_STATISTIC_genreg__" => "Generating Regression" )
genreg = (genreg = ["Probit", "Probit","Logit","Logit"],)
regtable(rr1, rr2,rr3,rr4; custom_statistics=genreg, labels = labels)
```
I think the Tuple is cumbersome, and I'd prefer to have the option for this to appear as a separate block (like in the OP's example: Controls: Yes), rather than with the other statistics.
