### ISSUE TITLE
HTML Output Option

### ISSUE THREAD

**Issue by ldsands** [jmboehm/RegressionTables.jl#5]
I'm an R user (using stargazer) and my workflow is all based around HTML output so that I can convert in to MS Word for my collaborators. Any possibility of this?

**Comment by jmboehm** [comment]
I feel for you (regarding MS Word). Yes, HTML output is on my 'todo' list.

**Comment by jmboehm** [comment]
Fixed in the latest commit (d843b28f72fbee19778e338a9b9ea8688f037f8e). See the readme.md.

If you want to have a slightly different HTML look than the one that I implemented, you can create a function like the one in src/rendersettings/html.jl and pass it to the `regtable` function.

**Comment by ldsands** [comment]
Thank you for your work! This brings Julia that much closer to being able to replace most of my R work for me.
