### ISSUE TITLE
How to adjust number of decimal places outputed by `latexOutput()`

### ISSUE THREAD

**Issue by alexboche** [jmboehm/RegressionTables.jl#86]
I would like to create a Latex regression table from some GLM and/or FIxedEffectModels regressions. 
I have `regtable(sm1a, sm1b; renderSettings = latexOutput())`. This prints out the regression table with 3 digits after the decimal. I would like to make that 4 digits after the decimal. How can I do this? 
Thanks.

**Comment by jmboehm** [comment]
From the readme:

> estimformat is a String that describes the format of the estimate. Defaults to "%0.3f".

Hence `estimformat = "%0.4f"` does what you are looking for.
