### ISSUE TITLE
API to adhere to?

### ISSUE THREAD

**Issue by jsams** [jmboehm/RegressionTables.jl#9]
Is there a public API that if we implement (e.g. coeffs/stderr/rsq/lklhd/bic/aic/etc. functions), we can send our models to your function and have everything work?

I suspect it is ideal for you and users if you don't go down the path of stargazer and try to implement extraction code for every model type out there. Rather, I suspect it is better if you declare a minimum/suggested/full set of functions that if they work with the model object, your code can still produce nice tables.

I write a fair amount of custom estimators, and one of the frustrating things is that, after having put in all that work to get the estimator to work, that there isn't a standard way to output to a nice table. This kind of solution would ostensibly mean I just have to implement a handful of functions for my output object and be good to go.

In any case, thanks for the package!

**Comment by jmboehm** [comment]
Yes, one of the types that the package can take is a `DataFrameRegressionModel` from the StatsModels package:
https://github.com/JuliaStats/StatsModels.jl/blob/master/src/statsmodel.jl
Does that work for you?

**Comment by jsams** [comment]
Maybe. It's hard to know what's going on without a great deal more context about the code. More to the point, it's not clear which parts you need and which parts you don't. The fact that there's things like coeftable(), r2(), etc. functions is promising. But it's not clear what YOU need to construct the output. Which I think is the point of an API: to abstract from the context and to just tell me what I need to give you and how you'll treat it to get the output. 

For example, I hope you don't need the ModelMatrix . . . mine doesn't exist (well, only 1 line at a time does). Further, you say you support all these regression statistics, but it is not at all clear how you do that from the code on that page. And what about statistics you don't list there? (AIC, BIC, Likelihood, J-tests, 1st stage F in an IV regression)

**Comment by Nosferican** [comment]
Aye. I would be happy to add `has_iv`, `has_fe`, `vce`, `islinear`, and other methods. I would envision making it such that any package that implements the StatsBase abstraction for RegressionModel gets the the regtables for free.

**Comment by jmboehm** [comment]
Closing this as `RegressionModel` and `TableRegressionModel` are both now supported.
