### ISSUE TITLE
Is it possible to report the table to Excel?

### ISSUE THREAD

**Issue by davidxiaoyuxu** [jmboehm/RegressionTables.jl#94]
It's more flexible to first report results to Excel, where the table can be modified, and then use Excel's add-in "excel2latex" to create the tex format.

**Comment by jmboehm** [comment]
I have no plans of supporting excel export (in my view, the advantage of using a package like this is that you just run code to create the tables, so it makes results more easily replicable). I think the best workaround would be to export to HTML, and then run some HTML to Excel conversion script.

What are the manual edits that you would like to be able to do? Maybe we could put them into the package?

**Comment by davidxiaoyuxu** [comment]
Thanks! The replicability concern makes sense. 

The manual edits are usually modifying table details, such as adding text to specific cells and changing horizontal lines. I took a look at your papers (btw they look amazing). If the tables in your papers are directly generated by this program, I think I don't need manual edits for most of the cases. This package will probably change the workflow of my future empirical projects!
